<a href="https://colab.research.google.com/github/bubs-art/Data-Analytics/blob/main/Numpy_mini_proj_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#NumPy mini proj 1
'''Objective: Assess understanding of array creation, manipulation, and matrix operations
Tasks:
- Create a 5×5 NumPy array filled with random integers between 1 and 50.✅
- Replace all even numbers with -1 without using loops.✅
- Compute the sum of each row and store it in a new array.✅
- Compute the dot product of the matrix with its transpose.✅
- Find the index of the maximum element in the matrix.✅
🔹 Concepts Tested: Array manipulation, indexing, broadcasting, and matrix operations'''

In [ ]:
import numpy as np

m = np.random.randint(1,50,size = (5,5))

m[m%2==0] = -1

sum = np.sum(m,axis = 1)

dot = np.dot(m,m.T)

max = np.argmax(m)

print(f"even numbers = -1: {m}")
print(f"Sum of each row is stored in {sum}")
print(f"dot product is {dot}")
print(f"Index of the maximum element is {max}")





even numbers = -1: [[-1 -1 -1 -1 25]
 [45 -1 -1 15 -1]
 [-1 37 -1 45 49]
 [33 47  7 -1 23]
 [ 3 -1  9 17 -1]]
Sum of each row is stored in [ 21  57 129 109  27]
dot product is [[ 629  -83 1145  489  -53]
 [ -83 2253  545 1393  383]
 [1145  545 5797 2781  667]
 [ 489 1393 2781 3877   75]
 [ -53  383  667   75  381]]
Index of the maximum element is 14
